image: Ubuntu
skip_tags: true

install:
- |
  npm install

build_script:
- |
  npm run build

artifacts:
- path: public

for:
- branches:
    only:
      - master

  before_deploy:
    - |
      git config --global user.email "dubcio@o2.pl"
      git config --global user.name "AppVeyor CI/CD"
      git config --global credential.helper store
      echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" >> ~/.git-credentials

  deploy_script:
  - |
    npm run deploy
