image: Ubuntu
skip_tags: true

install:
- |
  npm install

build_script:
- |
  echo "TODO: define build script"

artifacts:
- path: public

before_deploy:
- |
  git config --global user.email "dubcio@o2.pl"
  git config --global user.name "AppVeyor CI/CD"
  git config --global credential.helper store
  echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" >> ~/.git-credentials
- |
  npm run deploy

deploy_script:
- |
  echo "TODO: figure out when it is executed"
