:page-type: blog
:page-category: general

= Hello World!
Bart Dubois
D1, 2021-02-11

Welcome to origami.network first blog post.

When you start to learn a new programming language, typically the first example is the _Hello World_.
This way you get the idea of how the program is structured, what are the simplest syntax elements, how to communicate with the external world, and finally how to make it live by running it.
For me, this post is like such _Hello World_ where the output will not go on the screen but to the audience, you.

I know, I should keep it short and as informative as possible.
Let's start then with what you could find here in the feature.

Generally, all the things related to _software folding_.
How to organize your software workshop by getting all the best things and achievements of software engineering, and apply them to make your project better or at last more enjoyable.
I will not focus on any particular technology or methodology.
Instead, I will combine and mix them to show how they can complement each other to create more complicated structures without losing the simplicity,
Whatever we will look from the perspective of the domain or single line of code.
Just like with a piece of paper and a simple set of folding rules.

If it still sounds mysterious, that's fine. 
I hope to interest you enough to pass by here from time to time.

Because I like to combine sharing with learning, I will not be myself if it will not be the case here.
Together with the maintenance of the page and writing the post I would like to improve my language skills while I'm not naive English speaker.
I will touch the technology that I work on a day-by-day basis, but also take to the workshop the ones that I never use or was afraid of before.
You can see that the page is very raw now, I hope it will improve as part of the journey as well.

I'm still wondering how to create some feedback channels.
Just in case you would like to say _Hello Bart_.
As a starting point, I would like to use GitHub Discussion on this page repository.
In the end, this is the page about software and the discussion capability is the new thing on GitHub.

Thank you and see you soon.
Bart.
