:page-type: blog
:page-category: general

= Hello World!
Bart Dubois
1, 2021-05-16

Welcome to *origami.network* first blog post.

When you start to learn a new programming language, typically the first example is the _Hello World_.
This way you get the idea of how the program is structured, what are the simplest syntax elements, how to communicate with the external world, and finally how to make it live by running it.
For me, this post is like such _Hello World_ where the output will not go on the screen but to the audience, you.

I know, I should keep it short and as informative as possible.
Let's start then with what you could find here in the future.

Generally, all the things related to *software folding*.
How to organize your software workshop by getting all the best things and achievements of software engineering, and apply them to make your project better or at least more enjoyable.
I will not focus on any particular technology or methodology.
Instead, I will combine and mix them to show how they can complement each other to create more complicated structures without losing their simplicity.
Whatever we will look from the perspective of the whole system or a single line of code, the same principles can be applied.
Just like with a piece of paper and a simple set of folding rules.

If it still sounds mysterious, that's fine. 
I hope I interested you enough that you will visit this page from time to time.

Because I like to combine sharing with learning, I will not be myself if it will not be the case here.
Together with the maintenance of the page and writing the post I would like to improve my language skills while I'm not a native English speaker.
I will touch the technology that I work on a daily basis, but also take to the workshop the ones that I have never used before or I was afraid of.
You can see that the page is very basic at the moment, but I hope it will improve over time.
This should be part of my journey.

I still wonder how to create some feedback channels.
Just in case you would like to say _Hello Bart_.
As a starting point, feel free to use https://github.com/origami-network/origami-network.github.io/discussions[GitHub Discussion on this site repository].
In the end, this is the page about software engineering and the discussion capability is the new thing on GitHub, the place where most software starts its life.
So let's try it.

Thank you and see you soon.

Bart.
